### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by lbertenasco** [git-token/documentation#8]
Hi, just found this project through a search on GH.

Could you elaborate more on this?

It looks interesting :)

**Comment by Ryanmtate** [comment]
Hey! Just saw your issues event pop up on the contract! You're my first outside contributor! 👍  ❤️ 

In short, GitToken is a project that uses a GitHub webhook to listen for git contributors and map those contributions to [Ethereum](https://www.ethereum.org/) ERC20 token distributions. I am currently working on a dashboard for the project here at https://gittoken.org/ (It's buggy, so be warned!)

In a nutshell, the goals for GitToken are to provide:

1. Another method for projects to incentivize open source collaboration and raise funding for their contributions by issuing tokens that are directly associated with the work that is being done on the project.

2. Better tools for evaluating token offerings and provide more tangible performance metrics that can be tied to a nominally represented value for each token.

3. Access to primary and secondary markets for contributors to swap tokens amongst other ERC20 assets.



Contributions being made to the project are currently being tracked by a webhook. Although I am still developing the services, all contributions being made to the repo right now (including this one) will be replayed in a live contract on the network and tokens will be issued to contributors.

Right now, creating a new issue is worth 500 tokens (subject to change as I further work on the economics of the model). 

You may claim your tokens at https://gittoken.org/ using [MetaMask](https://metamask.io/) to login and set your RPC provider to a private testnet => https://gittoken.org/web3/ (http://138.68.225.133:8545)

As I develop, I inevitably need to rebuild the contracts and don't replay all events immediately; so some contributions may disappear before the actual launch.

Disclosure: All tokens at the moment are valueless test net tokens and with the sole utility being the development of the contracts and services before launching live. These tokens should not be traded or perceived as having any current value while the project is under development.


Thanks again for checking out the project! Stay tuned for more information!

**Comment by lbertenasco** [comment]
Nice!
I now have **2500** git-tokens 🎉 
Do you have a `@gittoken.org` email to stay in touch?

**Comment by Ryanmtate** [comment]
I currently have the reward at 500 for each issue (new) event; but yes, there are 2500 tokens currently open! 🚀 

I absolutely want to stay in touch! I have an email setup for `ryan.tate@gittoken.io`. Please feel free to email me! Also, any git contributions are always welcome :)

Will get one setup for `.org` soon, it is not configured just yet.

**Comment by lbertenasco** [comment]
Email sent!
Closing the issue 😜
